FROM python:3.11-slim
WORKDIR /app
COPY . /app
RUN pip install --upgrade pip
RUN pip install -r api/requirements.txt
RUN pip install botbuilder-core aiohttp requests
CMD ["python", "bots/teams/app.py"]
